server:
  port: 8080
spring:
  messages:
    basename: messages
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /admin/h2-console
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
logging:
  level:
    root: WARN
    nl.promedico.demo.springboot: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG